# Generated by Django 6.0.2 on 2026-03-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('courses', '0004_coursemodule'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('FULL', 'Full Course'), ('MODULE', 'Module')], default='FULL', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.coursemodule'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'batch', 'module'), name='unique_student_batch_module_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('enrollment_type', 'FULL'), ('module__isnull', True)), models.Q(('enrollment_type', 'MODULE'), ('module__isnull', False)), _connector='OR'), name='enrollment_type_module_consistency'),
        ),
    ]
