# Generated by Django 6.0.2 on 2026-03-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_question_correct_answer_question_option_a_and_more'),
        ('courses', '0004_coursemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='courses.coursemodule'),
        ),
    ]
