# Generated by Django 6.0.2 on 2026-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_trainerprofile_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TRAINER', 'Trainer'), ('STUDENT', 'Student')], default='STUDENT', max_length=15),
        ),
    ]
