# Generated by Django 6.0.2 on 2026-03-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('courses', '0005_alter_coursetopic_options_coursetopic_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='courses.coursemodule'),
        ),
    ]
