# Generated by Django 6.0.2 on 2026-03-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursetopic_topicacknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_marked_taught', models.BooleanField(default=False)),
                ('trainer_marked_at', models.DateTimeField(blank=True, null=True)),
                ('student_marked_understood', models.BooleanField(default=False)),
                ('student_marked_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress_student_records', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.coursetopic')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress_trainer_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic__course__title', 'topic__topic_number', 'student__username'],
                'unique_together': {('topic', 'student', 'trainer')},
            },
        ),
    ]
