# Generated by Django 6.0.2 on 2026-03-17 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursemodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'ordering': ['course__title', 'module__order_number', 'topic_number', 'id']},
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.coursemodule'),
        ),
        migrations.AddConstraint(
            model_name='coursetopic',
            constraint=models.UniqueConstraint(fields=('module', 'topic_number'), name='unique_topic_number_per_module'),
        ),
    ]
