# Generated by Django 6.0.2 on 2026-03-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_attendancerecord'),
        ('courses', '0004_coursemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='courses.coursemodule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
