# Generated by Django 6.0.2 on 2026-03-16 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_module_attendancesession_module_and_more'),
        ('batches', '0001_initial'),
        ('courses', '0004_coursemodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='unique_attendance_session_per_batch_date',
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('batch', 'module', 'session_date'), name='unique_attendance_session_per_batch_module_date'),
        ),
    ]
