# Generated by Django 6.0.2 on 2026-03-17 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendancesession_unique_attendance_session_per_batch_date_and_more'),
        ('batches', '0002_batch_module'),
        ('courses', '0005_alter_coursetopic_options_coursetopic_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='unique_attendance_session_per_batch_module_date',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='courses.coursetopic'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('batch', 'topic', 'session_date'), name='unique_attendance_session_per_batch_topic_date'),
        ),
    ]
